<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>OBT_Invoices_Master</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>AnyCPU;x64</Platforms>
	<Version>0.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Config.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PDFium.forms.x64.v8-xfa" Version="4522.0.6" />
    <PackageReference Include="PdfiumViewer.Forms" Version="3.0.1" />
  </ItemGroup>

</Project>